version: 0.2

env:
  secrets-manager:
    CLAVIN_MAVEN_CENTRAL_USERNAME: "CLAVIN:MAVEN_CENTRAL_USERNAME"
    CLAVIN_MAVEN_CENTRAL_PASSWORD: "CLAVIN:MAVEN_CENTRAL_PASSWORD"
    CLAVIN_GPG_KEYNAME: "CLAVIN:GPG_KEYNAME"
    CLAVIN_GPG_PASSPHRASE: "CLAVIN:GPG_PASSPHRASE"
    CLAVIN_GPG_OWNERTRUST: "CLAVIN:GPG_OWNERTRUST"
    CLAVIN_GPG_SECRET_KEYS: "CLAVIN:GPG_SECRET_KEYS"
    
phases:
  install:
    runtime-versions:
      java: corretto11

  pre_build:
    commands:
      - pip3 install awscli --upgrade --user

  build:
    commands:
      - export UNAME=$CLAVIN_MAVEN_CENTRAL_USERNAME
      - export PWORD=$CLAVIN_MAVEN_CENTRAL_PASSWORD
      - export KEYNAME=$CLAVIN_GPG_KEYNAME
      - export PASSPHRASE=$CLAVIN_GPG_PASSPHRASE 
      - yum update -y
      - echo $CLAVIN_GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust
      - echo $CLAVIN_GPG_SECRET_KEYS | base64 --decode | gpg --import --no-tty --batch --yes  
      - mvn -s .release/settings.xml clean package deploy -B -Dmaven.test.skip=true -Prelease
