version: 0.2

env:
  secrets-manager:
    CLAVIN_MAVEN_CENTRAL_USERNAME: "CLAVIN:MAVEN_CENTRAL_USERNAME"
    CLAVIN_MAVEN_CENTRAL_PASSWORD: "CLAVIN:MAVEN_CENTRAL_PASSWORD"

phases:
  install:
    runtime-versions:
      java: corretto11

  pre_build:
    commands:
      - pip3 install awscli --upgrade --user

  build:
    commands:
      - export UNAME=$CLAVIN_MAVEN_CENTRAL_USERNAME
      - export PWORD=$CLAVIN_MAVEN_CENTRAL_PASSWORD
      - mvn -s .release/settings.xml clean package deploy
